// fs.js — walking the tree and reading it. One implementation, so every verb
// agrees on what is source, what is generated, and what is ignored.
import fs from "node:fs";
import path from "node:path";
import { ROOT, rel } from "./paths.js";
import { load } from "./config.js";
import * as kernel from "./kernel.js";

export const PROSE_SUFFIX = [".md", ".txt", ".rst", ".markdown", ".mdx"];
export const CODE_SUFFIX = [".js", ".mjs", ".cjs", ".ts", ".tsx", ".jsx", ".py", ".dart", ".go", ".rs",
  ".java", ".kt", ".rb", ".php", ".cs", ".swift", ".c", ".h", ".cpp", ".hpp", ".sh", ".bash", ".zsh",
  ".json", ".yaml", ".yml", ".toml", ".sql", ".html", ".css", ".scss", ".vue", ".svelte", ".xml",
  ".proto", ".tf", ".gradle", ".ex", ".exs", ".scala", ".lua", ".zig"];
export const SOURCE_SUFFIX = [...PROSE_SUFFIX, ...CODE_SUFFIX];
export const GENERATED_MARKERS = [/^\/\/\s*(@generated|Generated by|Code generated|DO NOT EDIT)/im,
  /^#\s*(Generated by|DO NOT EDIT)/im, /\.g\.dart$/, /\.freezed\.dart$/, /\.pb\.(go|js|ts|py)$/,
  /_pb2\.py$/, /\.generated\./, /\.d\.ts$/];

let _ignore = null;
function globToRe(g) {
  return new RegExp("^" + g.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "\0").replace(/\*/g, "[^/]*").replace(/\0/g, ".*") + "$");
}
export function ignoreRules() {
  if (_ignore) return _ignore;
  const cfg = load();
  const names = new Set();
  const globs = [];
  for (const g of cfg.workspace.ignore) { if (g.includes("*")) globs.push(globToRe(g)); else names.add(g); }
  // .gitignore at root: only the simple forms (name, dir/, *.ext). Enough to keep
  // node_modules-shaped trees out; anything subtler is a git question, not ours.
  try {
    for (const line of fs.readFileSync(path.join(ROOT, ".gitignore"), "utf8").split("\n")) {
      const l = line.trim();
      if (!l || l.startsWith("#") || l.startsWith("!")) continue;
      const clean = l.replace(/^\/+/, "").replace(/\/+$/, "");
      if (!clean || clean.includes("/")) continue;
      if (clean.includes("*")) globs.push(globToRe(clean)); else names.add(clean);
    }
  } catch { /* no .gitignore */ }
  _ignore = { names, globs };
  return _ignore;
}
export function isIgnored(name) {
  const { names, globs } = ignoreRules();
  return names.has(name) || globs.some((g) => g.test(name));
}

let _ignoreList = null;
/** The raw ignore list the kernel needs: names and globs as written, not compiled. */
function ignoreList() {
  if (_ignoreList) return _ignoreList;
  const cfg = load();
  const list = [...(cfg.workspace.ignore || [])];
  try {
    for (const line of fs.readFileSync(path.join(ROOT, ".gitignore"), "utf8").split("\n")) {
      const l = line.trim();
      if (!l || l.startsWith("#") || l.startsWith("!")) continue;
      const clean = l.replace(/^\/+/, "").replace(/\/+$/, "");
      if (clean && !clean.includes("/")) list.push(clean);
    }
  } catch { /* no .gitignore */ }
  _ignoreList = [...new Set(list)];
  return _ignoreList;
}

/** Every file under base (absolute paths), depth-first, ignoring the ignore set.
 *
 *  The kernel serves this whenever `bbk` is on the box: it is ~3x faster on a
 *  mid-sized tree and cannot blow the heap on a deep one. The JS below is the
 *  fallback and the contract — the selftest pins the two to the same file list,
 *  because a walk that quietly returns a different set is the silent failure
 *  every other verb inherits. */
export function walk(base = ROOT, opts = {}) {
  const { suffixes = SOURCE_SUFFIX, maxBytes = 2_000_000, includeHidden = false } = opts;
  const k = kernel.call("walk", { base: path.resolve(base), ignore: ignoreList(),
    suffixes: suffixes || [], max_bytes: maxBytes, include_hidden: includeHidden });
  if (k && Array.isArray(k.files)) return k.files.map((f) => f.path).sort();
  return walkJs(base, opts);
}

/** The JS walk, kept callable on its own so the parity check has something to
 *  compare against and `BB_KERNEL=` can force this path. */
export function walkJs(base = ROOT, { suffixes = SOURCE_SUFFIX, maxBytes = 2_000_000, includeHidden = false } = {}) {
  const out = [];
  const stack = [path.resolve(base)];
  while (stack.length) {
    const dir = stack.pop();
    let ents;
    try { ents = fs.readdirSync(dir, { withFileTypes: true }); } catch { continue; }
    for (const e of ents) {
      if (!includeHidden && e.name.startsWith(".") && e.name !== ".github") continue;
      if (isIgnored(e.name)) continue;
      const p = path.join(dir, e.name);
      if (e.isSymbolicLink()) continue;
      if (e.isDirectory()) { stack.push(p); continue; }
      if (!e.isFile()) continue;
      if (suffixes && suffixes.length && !suffixes.some((s) => e.name.endsWith(s))) continue;
      try { if (fs.statSync(p).size > maxBytes) continue; } catch { continue; }
      out.push(p);
    }
  }
  return out.sort();
}
export function readText(p, fallback = "") {
  try { return fs.readFileSync(p, "utf8"); } catch { return fallback; }
}
export function isGenerated(p, head = null) {
  if (GENERATED_MARKERS.some((m) => m.source.includes("$") && m.test(p))) return true;
  const h = head ?? readText(p).slice(0, 600);
  return GENERATED_MARKERS.some((m) => !m.source.includes("$") && m.test(h));
}
export function kindOf(p) {
  const s = String(p).toLowerCase();
  return PROSE_SUFFIX.some((x) => s.endsWith(x)) ? "prose" : "code";
}
export function langOf(p) {
  const e = path.extname(p).toLowerCase();
  return ({ ".js": "js", ".mjs": "js", ".cjs": "js", ".jsx": "js", ".ts": "ts", ".tsx": "ts", ".py": "py", ".dart": "dart",
    ".go": "go", ".rs": "rust", ".java": "java", ".kt": "kotlin", ".rb": "ruby", ".php": "php", ".cs": "csharp",
    ".swift": "swift", ".sh": "sh", ".bash": "sh", ".md": "md", ".vue": "vue", ".svelte": "svelte" })[e] || e.slice(1) || "other";
}
export { rel };
